name: iot-backend
services:
  node:
    build: node
    ports:
     - "88:88"
     - "3000:3000"
    volumes:
      - ./../:/usr/app
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=admin
      - DB_NAME=iot
    depends_on:
      - mysql
    networks:
      - iot-network
    command: npm run start

  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: iot
    networks:
      - iot-network
    volumes:
      - mysql-data:/var/lib/mysql

  emqx:
    image: emqx:5.8.3
    container_name: emqx
    environment:
      - "EMQX_NODE_NAME=emqx@node1.emqx.io"
      - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
      - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io,emqx@node2.emqx.io]"
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    networks:
      - iot-network
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083 

networks:
  iot-network:
    driver: bridge

volumes:
  mysql-data: